### ISSUE TITLE
Default eslint_path for Windows 10 Pro 64bit on Sublime Text 3 does not seem to work when there is a "whitespace" (aka a "space") inside profile user name.

### ISSUE THREAD

**Issue by bs-thomas** [TheSavior/ESLint-Formatter#66] opened 2018-08-25 15:42 UTC
```
  // The location of the globally installed eslint package to use as a fallback
  "eslint_path": {
    "windows": "%APPDATA%/npm/node_modules/eslint/bin/eslint",
    "linux": "/usr/bin/eslint",
    "osx": "/usr/local/bin/eslint"
  },
```

I see the default path settings for eslint_path (when it cannot find a local eslint binary) is "%APPDATA%/npm/node_modules/eslint/bin/eslint".

In the default path, there is my user folder "Thomas Cheng" (notice the space in between).  "Thomas Cheng" is also the equivalent environment variable %USERPROFILE%.

When I do the lint, it will return the following error:
![image](https://user-images.githubusercontent.com/2464920/44619981-fe17e980-a8bf-11e8-9750-26dcb2a3fb2f.png)

It captured the path "C:\Users\Thomas", but skipped the rest of the path due to the "whitespace" between Thomas Cheng.

Right now, my only workaround is to hardcode the path instead of using %APPDATA%.

Would appreciate if you could help take a quick look into this issue.

Thank you very much for your kind assistance, and afterall an amazing plugin!!  Thanks!

**Comment by 7NZ** [comment] 2019-09-23 08:39
i have this issue too,  #43  is the same as this issue,  still open after 2 year. i guess it will not be fix.

**Comment by skeggse** [comment] 2020-05-19 22:36
Marking as duplicate of #43.

**Closed by skeggse** 2020-05-19 22:36 UTC
